// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldServer.Infrastructure.Persistence;

#nullable disable

namespace WorldServer.Infrastructure.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260613113019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldServer.Domain.Entities.EntityRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ComplexProperty<Dictionary<string, object>>("BaseAttributes", "WorldServer.Domain.Entities.EntityRace.BaseAttributes#EntityAttributes", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Agility")
                                .HasColumnType("integer")
                                .HasColumnName("agility");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer")
                                .HasColumnName("dexterity");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer")
                                .HasColumnName("intelligence");

                            b1.Property<int>("Luck")
                                .HasColumnType("integer")
                                .HasColumnName("luck");

                            b1.Property<int>("Perception")
                                .HasColumnType("integer")
                                .HasColumnName("perception");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer")
                                .HasColumnName("strength");

                            b1.Property<int>("Vitality")
                                .HasColumnType("integer")
                                .HasColumnName("vitality");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("entity_races", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
