// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldServer.Domain.Entities.AbstractEntities;
using WorldServer.Infrastructure.Persistence;

#nullable disable

namespace WorldServer.Infrastructure.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260614021522_AtivePassiveEffects")]
    partial class AtivePassiveEffects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatusEffectIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.ActiveEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StatusEffectId")
                        .HasColumnType("uuid");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("StatusEffectId");

                    b.HasIndex("TargetId");

                    b.ToTable("active_effects", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.EntityRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ComplexProperty<Dictionary<string, object>>("BaseAttributes", "WorldServer.Domain.Entities.EntityRace.BaseAttributes#EntityAttributes", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Charm")
                                .HasColumnType("integer")
                                .HasColumnName("charm");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer")
                                .HasColumnName("dexterity");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer")
                                .HasColumnName("intelligence");

                            b1.Property<int>("Luck")
                                .HasColumnType("integer")
                                .HasColumnName("luck");

                            b1.Property<int>("Perception")
                                .HasColumnType("integer")
                                .HasColumnName("perception");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer")
                                .HasColumnName("strength");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActiveTitleId")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ChunkX")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkY")
                        .HasColumnType("integer");

                    b.Property<float>("LocalX")
                        .HasColumnType("real");

                    b.Property<float>("LocalY")
                        .HasColumnType("real");

                    b.Property<float>("LocalZ")
                        .HasColumnType("real");

                    b.Property<string>("Prefab")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaceID")
                        .HasColumnType("uuid");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Attributes", "WorldServer.Domain.Entities.Player.Attributes#EntityAttributes", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Charm")
                                .HasColumnType("integer")
                                .HasColumnName("charm");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer")
                                .HasColumnName("dexterity");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer")
                                .HasColumnName("intelligence");

                            b1.Property<int>("Luck")
                                .HasColumnType("integer")
                                .HasColumnName("luck");

                            b1.Property<int>("Perception")
                                .HasColumnType("integer")
                                .HasColumnName("perception");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer")
                                .HasColumnName("strength");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Resources", "WorldServer.Domain.Entities.Player.Resources#EntityResources", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CurrentHealth")
                                .HasColumnType("integer")
                                .HasColumnName("current_health");

                            b1.Property<int>("CurrentMana")
                                .HasColumnType("integer")
                                .HasColumnName("current_mana");

                            b1.Property<int>("MaxHealth")
                                .HasColumnType("integer")
                                .HasColumnName("max_health");

                            b1.Property<int>("MaxMana")
                                .HasColumnType("integer")
                                .HasColumnName("max_mana");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActiveTitleId");

                    b.HasIndex("RaceID");

                    b.HasIndex("ChunkX", "ChunkY");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.PlayerTitle", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("player_titles", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.StatusEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasVisualEffect")
                        .HasColumnType("boolean");

                    b.Property<List<EntityModifier>>("Modifiers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("status_effects", (string)null);
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.ActiveEffect", b =>
                {
                    b.HasOne("WorldServer.Domain.Entities.StatusEffect", null)
                        .WithMany()
                        .HasForeignKey("StatusEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.Player", b =>
                {
                    b.HasOne("Title", null)
                        .WithMany()
                        .HasForeignKey("ActiveTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorldServer.Domain.Entities.EntityRace", null)
                        .WithMany()
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldServer.Domain.Entities.PlayerTitle", b =>
                {
                    b.HasOne("WorldServer.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Title", null)
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
